apiVersion: v1
kind: DeploymentConfig
metadata:
  name: webserver
  namespace: presto
spec:
  selector:
    name: webserver
  replicas: 1
  template:
    metadata:
      labels:
        name: webserver
    spec:
      containers:
        - name: webserver
          image: centos/httpd-24-centos7:latest
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1G
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: shared-vol
              mountPath: /var/www/html/data
              readOnly: true
      volumes:
        - name: shared-vol
          persistentVolumeClaim:
            claimName: presto-data-share
---
kind: Service
apiVersion: v1
metadata:
  name: webserver
  namespace: presto
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    name: webserver
  sessionAffinity: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: webserver
  namespace: presto
spec:
  to:
    kind: Service
    name: webserver
    weight: 100
  port:
    targetPort: web
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None