apiVersion: v1
kind: DeploymentConfig
metadata:
  name: presto-cli
  namespace: presto
  labels:
    app: presto-cli
spec:
  selector:
    app: presto-cli
  replicas: 1
  template:
    metadata:
      labels:
        app: presto-cli
    spec:
      containers:
        - name: presto-cli
          image: 'quay.io/guimou/tpcds-gen:338'
          command: [ "tail", "-f", "/dev/null" ]
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 2
              memory: 2G
          volumeMounts:
            - name: shared-vol
              mountPath: /data
      volumes:
        - name: shared-vol
          persistentVolumeClaim:
            claimName: presto-data-share
