apiVersion: batch/v1
kind: Job
metadata:
  name: 05-tpcds-create-dataset-sf3000
  namespace: presto
spec:
  selector: {}
  template:
    metadata:
      name: 05-tpcds-create-dataset-sf3000
    spec:
      volumes:
        - name: shared-vol
          persistentVolumeClaim:
            claimName: presto-data-share
      containers:
        - name: presto-cli
          image: 'quay.io/guimou/tpcds-gen:338'
          imagePullPolicy: Always
          command: [/opt/tpcds-gen.sh]
          volumeMounts:
            - name: shared-vol
              mountPath: /data
          env:
            - name: SCALE
              value: '3000'
            - name: PRESTO_SERVER
              value: 'presto-service:8080'
            - name: FORMAT
              value: 'parquet'
            - name: SCHEMA
              value: 'tpcds_sf$(SCALE)_$(FORMAT)'
            - name: LOCATION
              value: 's3://presto-test-bucket/sf$(SCALE)/$(SCHEMA).db/'       
      restartPolicy: Never
