apiVersion: batch/v1
kind: Job
metadata:
  name: 11-tpcds-benchmark-sf1
  namespace: presto
spec:
  selector: {}
  template:
    metadata:
      name: 01-tpcds-create-table-sf1
    spec:
      volumes:
        - name: shared-vol
          persistentVolumeClaim:
            claimName: presto-data-share
      containers:
        - name: presto-cli
          image: 'quay.io/guimou/prestosql-cli:338'
          imagePullPolicy: Always
          command: [/opt/tpcds-gen.sh]
          volumeMounts:
            - name: shared-vol
              mountPath: /data
          env:
            - name: SCALE
              value: '1'
            - name: PRESTO_SERVER
              value: 'presto-service:8080'
            - name: FORMAT
              value: 'parquet'
            - name: SCHEMA
              value: 'tpcds_sf$(SCALE)_parquet'
            - name: LOCATION
              value: 's3://presto-test-bucket/sf$(SCALE)/tpcds_sf$(SCALE)_parquet.db/'       
      restartPolicy: Never
